/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Class.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Editresident extends javax.swing.JFrame {

    
    public Editresident() {
        initComponents();
         showinfo();
    }
    Connection conn = new DBConnection().connect();
    PreparedStatement ps;
     ResultSet rs;
    String v;
 Editresident(String value) {  
        initComponents();
         this.v = value;

        
       
        showinfo();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        h = new JTextFieldPersonalizado.JCTextField();
        bbb2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        spouse = new JTextFieldPersonalizado.JCTextField();
        contact = new JTextFieldPersonalizado.JCTextField();
        w = new JTextFieldPersonalizado.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        mother = new JTextFieldPersonalizado.JCTextField();
        father = new JTextFieldPersonalizado.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        childno = new JTextFieldPersonalizado.JCTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        permanentaddr = new JTextFieldPersonalizado.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        house = new JTextFieldPersonalizado.JCTextField();
        jLabel24 = new javax.swing.JLabel();
        street = new JTextFieldPersonalizado.JCTextField();
        jLabel25 = new javax.swing.JLabel();
        brgy = new JTextFieldPersonalizado.JCTextField();
        jLabel26 = new javax.swing.JLabel();
        municipal = new JTextFieldPersonalizado.JCTextField();
        jLabel27 = new javax.swing.JLabel();
        prov = new JTextFieldPersonalizado.JCTextField();
        residencydate = new JTextFieldPersonalizado.JCTextField();
        jPanel11 = new javax.swing.JPanel();
        occupation = new JTextFieldPersonalizado.JCTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lname = new JTextFieldPersonalizado.JCTextField();
        fname = new JTextFieldPersonalizado.JCTextField();
        mname = new JTextFieldPersonalizado.JCTextField();
        lbl = new javax.swing.JLabel();
        bbb5 = new javax.swing.JLabel();
        bbb6 = new javax.swing.JLabel();
        bbb7 = new javax.swing.JLabel();
        bbb8 = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        headlabel4 = new javax.swing.JLabel();
        headlabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        educ = new JTextFieldPersonalizado.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        headlabel6 = new javax.swing.JLabel();
        headlabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pob = new JTextFieldPersonalizado.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        nationality = new JTextFieldPersonalizado.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        bbb3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        civilstatus = new JTextFieldPersonalizado.JCTextField();
        religion = new JTextFieldPersonalizado.JCTextField();
        sex = new JTextFieldPersonalizado.JCTextField();
        dob = new JTextFieldPersonalizado.JCTextField();
        status = new JTextFieldPersonalizado.JCTextField();
        age = new JTextFieldPersonalizado.JCTextField();
        jSeparator14 = new javax.swing.JSeparator();
        headlabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1076, 612));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Height");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        h.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        h.setPlaceholder("Height");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        h.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hKeyReleased(evt);
            }
        });
        jPanel3.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, 30));

        bbb2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bbb2.setForeground(new java.awt.Color(102, 102, 102));
        bbb2.setText("Weight");
        bbb2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bbb2PropertyChange(evt);
            }
        });
        jPanel3.add(bbb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 56, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Contact No.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Spouse Name: ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, 50));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("No. Of Child:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 50));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 260, 40));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 10));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 20));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 20));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 20));

        spouse.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        spouse.setPlaceholder("Spouse Name");
        spouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseActionPerformed(evt);
            }
        });
        spouse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spouseKeyReleased(evt);
            }
        });
        jPanel3.add(spouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, 30));

        contact.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        contact.setPlaceholder("Contact No.");
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactKeyReleased(evt);
            }
        });
        jPanel3.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 170, 30));

        w.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        w.setPlaceholder("Weight");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });
        w.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                wKeyReleased(evt);
            }
        });
        jPanel3.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 170, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Mother Name:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 50));

        mother.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        mother.setPlaceholder("Mother name");
        mother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherActionPerformed(evt);
            }
        });
        mother.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                motherKeyReleased(evt);
            }
        });
        jPanel3.add(mother, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, 30));

        father.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        father.setPlaceholder("Father Name");
        father.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherActionPerformed(evt);
            }
        });
        father.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fatherKeyReleased(evt);
            }
        });
        jPanel3.add(father, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Father Name: ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 50));

        childno.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        childno.setPlaceholder("No. of Child");
        childno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childnoActionPerformed(evt);
            }
        });
        childno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                childnoKeyReleased(evt);
            }
        });
        jPanel3.add(childno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 260, 290));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Date of Residency:");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 20));

        permanentaddr.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        permanentaddr.setPlaceholder("Permanent Address");
        permanentaddr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permanentaddrActionPerformed(evt);
            }
        });
        permanentaddr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                permanentaddrKeyReleased(evt);
            }
        });
        jPanel6.add(permanentaddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 370, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Permanent Address:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 40));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("House No.:");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        house.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        house.setPlaceholder("House No.");
        house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseActionPerformed(evt);
            }
        });
        house.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                houseKeyReleased(evt);
            }
        });
        jPanel6.add(house, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 230, 30));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Purok / District:");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 30));

        street.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        street.setPlaceholder("Purok");
        street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetActionPerformed(evt);
            }
        });
        street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                streetKeyReleased(evt);
            }
        });
        jPanel6.add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, 30));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Barangay:");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        brgy.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        brgy.setPlaceholder("Barangay");
        brgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brgyActionPerformed(evt);
            }
        });
        brgy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brgyKeyReleased(evt);
            }
        });
        jPanel6.add(brgy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, 30));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Municipality:");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 30));

        municipal.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        municipal.setPlaceholder("Municipality");
        municipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipalActionPerformed(evt);
            }
        });
        municipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                municipalKeyReleased(evt);
            }
        });
        jPanel6.add(municipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 230, 30));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Province:");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        prov.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        prov.setPlaceholder("Province");
        prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provActionPerformed(evt);
            }
        });
        prov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                provKeyReleased(evt);
            }
        });
        jPanel6.add(prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 230, 30));

        residencydate.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        residencydate.setPlaceholder("Date of residency");
        residencydate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencydateActionPerformed(evt);
            }
        });
        residencydate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                residencydateKeyReleased(evt);
            }
        });
        jPanel6.add(residencydate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 230, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 430, 420));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        occupation.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        occupation.setPlaceholder("Employment Status");
        occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationActionPerformed(evt);
            }
        });
        occupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                occupationKeyReleased(evt);
            }
        });
        jPanel11.add(occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, 30));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Employment Status:");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 310, 80));

        jPanel9.setBackground(new java.awt.Color(59, 89, 152));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-go-back-30.png"))); // NOI18N
        jLabel11.setText("Go back");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jLabel11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel11KeyPressed(evt);
            }
        });
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 100, 29));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-save-30.png"))); // NOI18N
        jLabel20.setText("Update");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jLabel20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel20KeyPressed(evt);
            }
        });
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 80, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-resident-30.png"))); // NOI18N
        jLabel2.setText("Edit Resident");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        jSeparator12.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 20, 30));

        jSeparator13.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 20, 30));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel9.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 18, 0, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lname.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        lname.setPlaceholder("Surname");
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnameKeyReleased(evt);
            }
        });
        jPanel2.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 130, -1));

        fname.setToolTipText("");
        fname.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        fname.setPlaceholder("First Name");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, -1));

        mname.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        mname.setPlaceholder("Middlename");
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        mname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mnameKeyReleased(evt);
            }
        });
        jPanel2.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 140, -1));

        lbl.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl.setForeground(new java.awt.Color(102, 102, 102));
        lbl.setText("TBC-000");
        lbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblPropertyChange(evt);
            }
        });
        jPanel2.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, 40));

        bbb5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bbb5.setForeground(new java.awt.Color(102, 102, 102));
        bbb5.setText("Firstname");
        bbb5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bbb5PropertyChange(evt);
            }
        });
        jPanel2.add(bbb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 70, 40));

        bbb6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bbb6.setForeground(new java.awt.Color(102, 102, 102));
        bbb6.setText("Middle Name");
        bbb6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bbb6PropertyChange(evt);
            }
        });
        jPanel2.add(bbb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 80, 40));

        bbb7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bbb7.setForeground(new java.awt.Color(102, 102, 102));
        bbb7.setText("Last Name");
        bbb7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bbb7PropertyChange(evt);
            }
        });
        jPanel2.add(bbb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 70, 40));

        bbb8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bbb8.setForeground(new java.awt.Color(102, 102, 102));
        bbb8.setText("Resident ID:");
        bbb8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bbb8PropertyChange(evt);
            }
        });
        jPanel2.add(bbb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 40));

        res.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        res.setForeground(new java.awt.Color(102, 102, 102));
        res.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                resPropertyChange(evt);
            }
        });
        jPanel2.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, -1));

        headlabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        headlabel4.setForeground(new java.awt.Color(0, 0, 102));
        headlabel4.setText("BASIC INFO");
        jPanel1.add(headlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 40));

        headlabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        headlabel5.setForeground(new java.awt.Color(0, 0, 102));
        headlabel5.setText("Other Details");
        jPanel1.add(headlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 130, 30));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        educ.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        educ.setPlaceholder("Highest Education Attain");
        educ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educActionPerformed(evt);
            }
        });
        educ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                educKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Highest Education Attain:");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(educ, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(educ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 310, 80));

        headlabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        headlabel6.setForeground(new java.awt.Color(0, 0, 102));
        headlabel6.setText("ADDRESS:");
        jPanel1.add(headlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 120, 30));

        headlabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        headlabel9.setForeground(new java.awt.Color(0, 0, 102));
        headlabel9.setText("Occupation");
        jPanel1.add(headlabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 130, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pob.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        pob.setPlaceholder("Place of Birth");
        pob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobActionPerformed(evt);
            }
        });
        pob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pobKeyReleased(evt);
            }
        });
        jPanel4.add(pob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 230, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sex:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        nationality.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        nationality.setPlaceholder("Nationality");
        nationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityActionPerformed(evt);
            }
        });
        nationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nationalityKeyReleased(evt);
            }
        });
        jPanel4.add(nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Place of Birth:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 110, 40));

        bbb3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bbb3.setForeground(new java.awt.Color(102, 102, 102));
        bbb3.setText("Birthday:");
        bbb3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bbb3PropertyChange(evt);
            }
        });
        jPanel4.add(bbb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 56, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 10, 370));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Age:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 40));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Nationality");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 50));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Religion:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 50));
        jPanel4.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 10));
        jPanel4.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 20));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Civil Status:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 40));
        jPanel4.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 20));
        jPanel4.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 20));
        jPanel4.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 20));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Resident Status:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, 40));

        civilstatus.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        civilstatus.setPlaceholder("Religion");
        civilstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilstatusActionPerformed(evt);
            }
        });
        civilstatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                civilstatusKeyReleased(evt);
            }
        });
        jPanel4.add(civilstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 30));

        religion.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        religion.setPlaceholder("Religion");
        religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionActionPerformed(evt);
            }
        });
        religion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                religionKeyReleased(evt);
            }
        });
        jPanel4.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 150, 30));

        sex.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        sex.setPlaceholder("Sex");
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        sex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sexKeyReleased(evt);
            }
        });
        jPanel4.add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 30));

        dob.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        dob.setPlaceholder("Birthdate");
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobKeyReleased(evt);
            }
        });
        jPanel4.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 150, 30));

        status.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        status.setPlaceholder("Resident Status");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                statusKeyReleased(evt);
            }
        });
        jPanel4.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 230, 30));

        age.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        age.setPlaceholder("Age");
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageKeyReleased(evt);
            }
        });
        jPanel4.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, 30));
        jPanel4.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, 420));

        headlabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        headlabel7.setForeground(new java.awt.Color(0, 0, 102));
        headlabel7.setText("EDUCATION");
        jPanel1.add(headlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void hKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_hKeyReleased

    private void bbb2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bbb2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bbb2PropertyChange

    private void spouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseActionPerformed

    private void spouseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spouseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseKeyReleased

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_contactKeyReleased

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wActionPerformed

    private void wKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_wKeyReleased

    private void motherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherActionPerformed

    private void motherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_motherKeyReleased

    private void fatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherActionPerformed

    private void fatherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fatherKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherKeyReleased

    private void permanentaddrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permanentaddrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permanentaddrActionPerformed

    private void permanentaddrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_permanentaddrKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_permanentaddrKeyReleased

    private void houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseActionPerformed

    private void houseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_houseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_houseKeyReleased

    private void streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetActionPerformed

    private void streetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_streetKeyReleased

    private void brgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brgyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brgyActionPerformed

    private void brgyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brgyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_brgyKeyReleased

    private void municipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipalActionPerformed

    private void municipalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_municipalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_municipalKeyReleased

    private void provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provActionPerformed

    private void provKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_provKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_provKeyReleased

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

        
       
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel11KeyPressed

    }//GEN-LAST:event_jLabel11KeyPressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
            int x = JOptionPane.showConfirmDialog(null,"Confirm Update Current Resident?","confirmation message", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE);
        if (x==0){ 
            Update1();
            
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel20KeyPressed

    }//GEN-LAST:event_jLabel20KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
      
    }//GEN-LAST:event_jTextField1KeyPressed

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
       
    }//GEN-LAST:event_lnameFocusLost

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyReleased

    }//GEN-LAST:event_lnameKeyReleased

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameKeyReleased

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void mnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameKeyReleased

    private void lblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPropertyChange

    private void bbb5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bbb5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bbb5PropertyChange

    private void bbb6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bbb6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bbb6PropertyChange

    private void pobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pobActionPerformed

    private void pobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pobKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pobKeyReleased

    private void nationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityActionPerformed

    private void nationalityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityKeyReleased

    private void religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionActionPerformed

    private void religionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_religionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_religionKeyReleased

    private void bbb3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bbb3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bbb3PropertyChange

    private void childnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childnoActionPerformed

    private void childnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_childnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_childnoKeyReleased

    private void residencydateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencydateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residencydateActionPerformed

    private void residencydateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_residencydateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_residencydateKeyReleased

    private void civilstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_civilstatusActionPerformed

    private void civilstatusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_civilstatusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_civilstatusKeyReleased

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void sexKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sexKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sexKeyReleased

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dobKeyReleased

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void statusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_statusKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_statusKeyReleased

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ageKeyReleased

    private void occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationActionPerformed

    private void occupationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_occupationKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationKeyReleased

    private void educActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educActionPerformed

    private void educKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_educKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_educKeyReleased

    private void bbb7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bbb7PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bbb7PropertyChange

    private void bbb8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bbb8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_bbb8PropertyChange

    private void resPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_resPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_resPropertyChange


  private void Update1(){
   try{
       String resid = res.getText().toUpperCase();
       String lastname = lname.getText().toUpperCase();
       String firstname = fname.getText().toUpperCase();
       String middlename = mname.getText().toUpperCase();
       String houseno = house.getText().toUpperCase();
       String streets = street.getText().toUpperCase();
       String barangay = brgy.getText().toUpperCase();
       String muni = municipal.getText().toUpperCase();
       String province = prov.getText().toUpperCase();
        String perma = permanentaddr.getText().toUpperCase();
          String placeofbirth = pob.getText().toUpperCase();
       String dateresidency = residencydate.getText().toUpperCase();
         String hei = h.getText().toUpperCase();
          String wei = w.getText().toUpperCase();
           String contactno = contact.getText().toUpperCase();
            String spousename = spouse.getText().toUpperCase();
             String child = childno.getText().toUpperCase();
             String nation = nationality.getText().toUpperCase();
             
       String birthday = dob.getText().toUpperCase();
       String a = age.getText().toUpperCase();
       int ag =Integer.valueOf(a);
       String reli = religion.getText().toUpperCase();
       String civil = civilstatus.getText().toUpperCase();
       String s = sex.getText().toUpperCase();
       int children = Integer.valueOf(child);
       String stat = status.getText().toUpperCase();
       String education = educ.getText().toUpperCase();
      String occu = occupation.getText().toUpperCase();
     
      String fath = father.getText().toUpperCase();
      String moth = mother.getText().toUpperCase();
     
      String  strh = hei.replaceAll("\'", Matcher.quoteReplacement("\\\'"));
          
          
       String ID = resid;
   
    
    String update1 = "UPDATE `tbl_resident` SET `last_name`='"+lastname+"',`first_name`='"+firstname+"',`middle_name`='"+middlename+"',`age`='"+ag+"',`sex`='"+s+"',`date_of_birth`='"+birthday+"',`place_of_birth`='"+placeofbirth+"',`height`='"+strh+"',`weight`='"+wei+"',`contact_no`='"+contactno+"',`permanent_add`='"+perma+"',`resident_stat`='"+stat+"',`highest_educ_attain`='"+education+"',`occupation`='"+occu+"',`civil_status`='"+civil+"',`spouse_name`='"+spousename+"',`no_of_child`='"+children+"',`religion`='"+reli+"',`nationality`='"+nation+"',`mother_name`='"+moth+"',`father_name`='"+fath+"',`date_residency`='"+dateresidency+"',`date_edited`= sysdate() WHERE `resident_id`='"+ID+"'";
     ps = conn.prepareStatement(update1);
    ps.executeUpdate();
    
    
    
    
    String update2 = "UPDATE `tbl_residentaddress` SET `house_no`='"+houseno+"',`purok`='"+streets+"',`barangay`='"+barangay+"',`municipality`='"+muni+"',`province`='"+province+"' WHERE  `addr_id`='"+ID+"'";
    ps = conn.prepareStatement(update2);
    ps.executeUpdate();
    JOptionPane.showMessageDialog(this, "Update Successfully!!");
        new Dashboard().resident_table();
   dispose();
   
   }
            catch (Exception e){
               JOptionPane.showMessageDialog(this, e); 
     }
   
    

    
    
    
}
  void showinfo(){
        try{ 
              
          String id = v;
           
            
            String query= "SELECT * FROM `tbl_resident`a INNER JOIN `tbl_residentaddress`b where a.resident_id = '"+id+"' AND b.addr_id ='"+id+"';" ; 
               
           ps=conn.prepareStatement(query);
            rs=ps.executeQuery();
           
           while (rs.next())
           {
               int rid = rs.getInt("resident_id");
               String resid = String.valueOf(rid);
                String lastname = rs.getString("last_name");
                 String firstname = rs.getString("first_name");
                  String middlename = rs.getString("middle_name");
                   int a = rs.getInt("age");
                    String s = rs.getString("Sex");
                    String birth = rs.getString("date_of_birth");
                     String birthplace = rs.getString("place_of_birth");
                      String height= rs.getString("height");
                       String weight = rs.getString("weight");
                        String con = rs.getString("contact_no");
                        
                          
                           String perm = rs.getString("permanent_add");
                           String stat = rs.getString("resident_stat");
                            
                              String educatt = rs.getString("highest_educ_attain");
                               String occu = rs.getString("occupation");
                                 String civil = rs.getString("civil_status");
                                  String sname = rs.getString("spouse_name");
                                   String child = rs.getString("no_of_child");
                                    String reli = rs.getString("religion");
                                     String nation = rs.getString("nationality");
                                      String moth = rs.getString("mother_name");
                                       String fath = rs.getString("father_name");
                                        String ag =String.valueOf(a);
                                        String houseno = rs.getString("house_no");
                                         String barangay = rs.getString("barangay");
                                          String p = rs.getString("purok");
                                          String muni = rs.getString("municipality");
                                          String province = rs.getString("province");
                                        String residen = rs.getString("date_residency");
                                         residencydate.setText(residen);
                                          res.setText(resid);                                                                                                             
                                            lname.setText(lastname);
                                         fname.setText(firstname);
                                         mname.setText(middlename);
                                          age.setText(ag);
                                          sex.setText(s);
                                          dob.setText(birth);
                                          pob.setText(birthplace);
                                          h.setText(height);
                                           w.setText(weight);
                                           contact.setText(con);
                                           permanentaddr.setText(perm);
                                           status.setText(stat);
                                           educ.setText(educatt);
                                           occupation.setText(occu);
                                           religion.setText(reli);
                                           civilstatus.setText(civil);
                                           spouse.setText(sname);
                                           childno.setText(child);
                                           nationality.setText(nation);
                                           mother.setText(moth);
                                           father.setText(fath);
                                            house.setText(houseno);
                                          street.setText(p);
                                          brgy.setText(barangay);
                                          municipal.setText(muni);
                                          prov.setText(province);
                                           
                                        
                                        
                                        
                                        
                                        
                                        
               
           }
            
                   
                  
                 }catch (Exception e){
                       
                        JOptionPane.showMessageDialog(this, e);
                 }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editresident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editresident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editresident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editresident.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editresident().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextFieldPersonalizado.JCTextField age;
    private javax.swing.JLabel bbb2;
    private javax.swing.JLabel bbb3;
    private javax.swing.JLabel bbb5;
    private javax.swing.JLabel bbb6;
    private javax.swing.JLabel bbb7;
    private javax.swing.JLabel bbb8;
    private JTextFieldPersonalizado.JCTextField brgy;
    private JTextFieldPersonalizado.JCTextField childno;
    private JTextFieldPersonalizado.JCTextField civilstatus;
    private JTextFieldPersonalizado.JCTextField contact;
    private JTextFieldPersonalizado.JCTextField dob;
    private JTextFieldPersonalizado.JCTextField educ;
    private JTextFieldPersonalizado.JCTextField father;
    private JTextFieldPersonalizado.JCTextField fname;
    private JTextFieldPersonalizado.JCTextField h;
    private javax.swing.JLabel headlabel4;
    private javax.swing.JLabel headlabel5;
    private javax.swing.JLabel headlabel6;
    private javax.swing.JLabel headlabel7;
    private javax.swing.JLabel headlabel9;
    private JTextFieldPersonalizado.JCTextField house;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl;
    private JTextFieldPersonalizado.JCTextField lname;
    private JTextFieldPersonalizado.JCTextField mname;
    private JTextFieldPersonalizado.JCTextField mother;
    private JTextFieldPersonalizado.JCTextField municipal;
    private JTextFieldPersonalizado.JCTextField nationality;
    private JTextFieldPersonalizado.JCTextField occupation;
    private JTextFieldPersonalizado.JCTextField permanentaddr;
    private JTextFieldPersonalizado.JCTextField pob;
    private JTextFieldPersonalizado.JCTextField prov;
    private JTextFieldPersonalizado.JCTextField religion;
    private javax.swing.JLabel res;
    private JTextFieldPersonalizado.JCTextField residencydate;
    private JTextFieldPersonalizado.JCTextField sex;
    private JTextFieldPersonalizado.JCTextField spouse;
    private JTextFieldPersonalizado.JCTextField status;
    private JTextFieldPersonalizado.JCTextField street;
    private JTextFieldPersonalizado.JCTextField w;
    // End of variables declaration//GEN-END:variables
}
